# Generated by Django 4.1.7 on 2023-04-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0005_autor_remove_livros_author_livros_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='app_name.autor'),
            preserve_default=False,
        ),
    ]
